#!/usr/bin/env zsh

# for f in */*.png; do
# 	f1=${f%.*}
# 	f2=${f1##*_}
# 	cp $f ${f%/*}/icon_$((f2/2))@2x.png
# done
# 
# rm */icon_8*

for f in *; do
	[[ -f ${f}/icon_256.png ]] || sips -z 256 256 ${f}/icon_128.png --out ${f}/icon_256.png
	[[ -f ${f}/icon_128@2x.png ]] || cp ${f}/icon_256.png ${f}/icon_128@2x.png
	[[ -f ${f}/icon_512.png ]] || sips -z 512 512 ${f}/icon_256.png --out ${f}/icon_512.png
	[[ -f ${f}/icon_256@2x.png ]] || cp ${f}/icon_512.png ${f}/icon_256@2x.png
	[[ -f ${f}/icon_512@2x.png ]] || sips -z 1024 1024 ${f}/icon_512.png --out ${f}/icon_512@2x.png
	mv ${f} ${f}.iconset
	iconutil -c icns ${f}.iconset
done